/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mxrck.autocompleter.TextAutoCompleter;
import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import controle.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import modelo.ModeloLoginUsuario;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 * @author vinicius
 */
public class AgendarReuniao extends javax.swing.JFrame {
    ConnectionConsulta conecta = new ConnectionConsulta();
     ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();


    /**
     * Creates new form AgendarReuniao
     */
    public AgendarReuniao() {
        initComponents();
        items();
        itemm();
        itemms();
        conecta.conectaBanco();
        
    }
    
     public void items (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldEvento);
        
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT evento from reuniao"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("evento"));
            }
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }

        public void itemm (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldSolicitante);
        
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT solicitante from reuniao"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("solicitante"));
            }
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }
        
          public void itemms (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldCliente);
        
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT cliente from reuniao"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("cliente"));
            }
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jSpinnerInicio = new javax.swing.JSpinner(sm);
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jDateChooserInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEvento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPessoas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSolicitante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        Date data = new Date();
        SpinnerDateModel tm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jSpinnerTermino = new javax.swing.JSpinner(tm);
        jComboBoxLocal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Reunião:");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinnerInicio, "HH:mm");
        jSpinnerInicio.setEditor(de);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDateChooserInicio.setDateFormatString("d/M/yyyy");

        jLabel2.setText("Evento:");

        jLabel3.setText("Local:");

        jComboBoxPessoas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Todos", "Parcial", "Cliente" }));
        jComboBoxPessoas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPessoasItemStateChanged(evt);
            }
        });
        jComboBoxPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPessoasActionPerformed(evt);
            }
        });

        jLabel5.setText("Solicitante:");

        jLabel6.setText("Cliente:");

        jTextFieldCliente.setText("Nulo");

        JSpinner.DateEditor sp = new JSpinner.DateEditor(jSpinnerTermino, "HH:mm");
        jSpinnerTermino.setEditor(sp);

        jComboBoxLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Sala Grande", "Sala Média", "Sala Pequena" }));

        jLabel4.setText("Participantes:");

        jLabel7.setText("Horário início:");

        jLabel8.setText("Horário final:");

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Criação de reuinao:");

        jLabel10.setText("Usuário:");

        jTextFieldUsuario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13))
                                            .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jComboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220)
                                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jDateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jSpinnerInicio)))))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel1)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jComboBoxPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(577, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPessoasActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jComboBoxPessoasActionPerformed

    private void jComboBoxPessoasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPessoasItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxPessoasItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //modelo = control.Primeiro();
        if(jComboBoxPessoas.getSelectedItem().equals("Sem seleção")){JOptionPane.showMessageDialog(null,"Selecione Participantes!");}
else{if(jTextFieldEvento.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha o campo Evento!");}
else{if(jComboBoxLocal.getSelectedItem().equals("")){JOptionPane.showMessageDialog(null,"Selecione o campo Local!");}
else{     
    
        }
        try{
        PreparedStatement pst = conecta.conn.prepareStatement("insert into reuniao (evento,local,datainicio,horarioinicio,horariotermino,participantes,solicitante,cliente)values (?,?,?,?,?,?,?,?)");
        pst.setString(1,jTextFieldEvento.getText());
        pst.setString(2, (String) jComboBoxLocal.getSelectedItem());
        SimpleDateFormat sdff=new SimpleDateFormat("d/M/yyyy");
        sdff.setTimeZone(TimeZone.getDefault());
        String sa=sdff.format(jDateChooserInicio.getDate());
        pst.setString(3,sa);
        //pst.setString(3, jDateChooserInicio.getDate().toString());
        SimpleDateFormat sdf=new SimpleDateFormat("kk:mm");
        sdf.setTimeZone(TimeZone.getDefault());
        String da=sdf.format(jSpinnerInicio.getValue());
        pst.setString(4,da);
        //SimpleDateFormat sdtf=new SimpleDateFormat("dd/MM/yyyy");
        //sdtf.setTimeZone(TimeZone.getDefault());
        //String la=sdtf.format(jDateChooserTermino.getDate());
        //pst.setString(5,la);
        SimpleDateFormat sd=new SimpleDateFormat("kk:mm");
        sd.setTimeZone(TimeZone.getDefault());
        String ta=sd.format(jSpinnerTermino.getValue());
        pst.setString(5,ta);
        pst.setString(6, (String) jComboBoxPessoas.getSelectedItem());
        jTextFieldSolicitante.setText(modelo.getLogin());
        pst.setString(7,jTextFieldSolicitante.getText()); 
        pst.setString(8,jTextFieldCliente.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
       
        } catch (SQLException ex) {                        
            JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
        }
}
        }
//         try{
//            SimpleEmail emailSimples = new SimpleEmail();
//            emailSimples.setHostName("200.170.82.150");
//            emailSimples.setSmtpPort(587);
//            emailSimples.setFrom(jTextFieldEmail.getText(),jTextFieldEmail.getText());          
//            emailSimples.addTo(jTextFieldEmail.getText());
//            emailSimples.setSubject(jLabelsubject.getText());
//            emailSimples.setMsg(jTextFieldDescricao.getText());  
//            emailSimples.setAuthentication("tecnologia@asscont.com.br","Asscont100");
//            emailSimples.send();  
//            JOptionPane.showMessageDialog(null, "Mensagem enviada");
//        } catch (EmailException ex) {
//            
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextFieldEvento.setText("");
        jComboBoxLocal.setSelectedItem("Sem seleção");
        jComboBoxPessoas.setSelectedItem("Sem seleção");
        jTextFieldSolicitante.setText("");
        jTextFieldCliente.setText("Nulo");
        
    }//GEN-LAST:event_jButton3ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarReuniao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxLocal;
    private javax.swing.JComboBox<String> jComboBoxPessoas;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooserInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerInicio;
    private javax.swing.JSpinner jSpinnerTermino;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldEvento;
    private javax.swing.JTextField jTextFieldSolicitante;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe){
        jTextFieldSolicitante.setText(recebe);
    }   
}
