/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.AtualizaDia;
import controle.AtualizadoHora;
import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloLoginUsuario;
import modelo.ModeloTabela;
import modelo.Usuario;

/**
 *
 * @author vinicius
 */
public class AgendaLigacoes extends javax.swing.JFrame {
    
    ConnectionConsulta conecta = new ConnectionConsulta();
    Usuario mod = new Usuario();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();

    /**
     * Creates new form AgendaLigacoes
     */
    public AgendaLigacoes() {
        initComponents();
        this.setExtendedState(this.getExtendedState()|VisualizadorProfissionais.MAXIMIZED_BOTH);
       // conecta.conectaBanco();
        preenchertabela("select * from telefones order by id");
        preenchertabelaa("select * from solicitacoes order by id");
        jTableTelefones.setAutoCreateRowSorter(true);
        jTableSolicitações.setAutoCreateRowSorter(true);
        AtualizadoHora.start(jLabelHora);  
        AtualizaDia.start(jLabelData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSolicitações = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSolicitante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTelefones = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPessoa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPessoaa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDados = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUsario = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxExito = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldObservacao = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextFieldTentativas = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldCel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableSolicitações.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableSolicitações.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSolicitaçõesMouseClicked(evt);
            }
        });
        jTableSolicitações.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableSolicitaçõesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSolicitações);

        jLabel1.setText("Solicitante:");

        jLabel2.setText("Departamento:");

        jLabel3.setText("Empresa/Pessoa:");

        jTextFieldEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmpresaKeyPressed(evt);
            }
        });

        jLabel4.setText("Cliente/Pessoa:");

        jTextFieldCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldClienteKeyPressed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        jLabel6.setText("Celular/Tel:");

        jTableTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefonesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTelefones);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Empresa/Pessoa:");

        jLabel8.setText("Cliente/Pessoa:");

        jLabel9.setText("Telefone:");

        jLabel10.setText("Celular/Tel:");

        jLabel11.setText("Dados adicionais:");

        jLabel12.setText("Usuario:");

        jTextFieldUsario.setEnabled(false);
        jTextFieldUsario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsarioActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setText("Tentativas:");

        jLabel14.setText("Êxito:");

        jComboBoxExito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Com Sucessso Celular", "Sem Sucesso Celular", "Com Sucesso Fixo", "Sem Sucesso Fixo" }));

        jLabel15.setText("Observação:");

        jTextFieldTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefoneKeyPressed(evt);
            }
        });

        jTextFieldCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCelularKeyPressed(evt);
            }
        });

        jLabel16.setText("Hora:");

        jLabel17.setText("Data:");

        jLabelHora.setText("Hora");

        jLabelData.setText("Data");

        jComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Contábil", "DP", "Declarações", "Diretoria", "Financeiro", "Fiscal", "Jurídico", "RH", "TI" }));

        jButton2.setText("Limpar Telefone");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpar Celular");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Limpar Tudo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextFieldId.setEnabled(false);

        jLabel18.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHora)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelData)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPessoaa, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDados, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(8, 8, 8)
                                                .addComponent(jTextFieldSolicitante)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(8, 8, 8)
                                                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEmpresa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxExito, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton6)))))
                                .addGap(6, 6, 6)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelData)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxExito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldObservacao)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonAlterar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPessoaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1336, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefonesMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableTelefones.getValueAt(jTableTelefones.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from telefones where id='"+ id +"'");
        
        try {
        conecta.rs.first();
        //jTextFieldId.setText(String.valueOf(conecta.rs.getInt("IdEntrevistas")));
        jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
        jTextFieldCliente.setText(conecta.rs.getString("cliente"));
        jTextFieldTelefone.setText(conecta.rs.getString("telefone"));
        jTextFieldCelular.setText(conecta.rs.getString("celular"));
//        jTextFieldCargo.setText(conecta.rs.getString("Cargo"));   
//        jTextFieldUsuario.setText(conecta.rs.getString("Usuario")); 
//        jComboBoxCompareceu.setSelectedItem(conecta.rs.getString("Compareceu"));
//        jComboBoxCorrigiu.setSelectedItem(conecta.rs.getString("Corrigiu"));
//        jComboBoxRetorno.setSelectedItem(conecta.rs.getString("Retorno"));
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableTelefonesMouseClicked

    private void jTextFieldClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
       
            mod.setPesquisa(jTextFieldCliente.getText());
            preenchertabela("select * from telefones where cliente like '%" + jTextFieldCliente.getText() + "%'");
         
        }
    }//GEN-LAST:event_jTextFieldClienteKeyPressed

    private void jTextFieldEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmpresaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      
            mod.setPesquisa(jTextFieldEmpresa.getText());
            preenchertabela("select * from telefones where empresa like '%" + jTextFieldEmpresa.getText() + "%'");
          
        }
    }//GEN-LAST:event_jTextFieldEmpresaKeyPressed

    private void jTextFieldTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            mod.setPesquisa(jTextFieldTelefone.getText());
            preenchertabela("select * from telefones where telefone like '%" + jTextFieldTelefone.getText() + "%'");
           
        }
    }//GEN-LAST:event_jTextFieldTelefoneKeyPressed

    private void jTextFieldCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCelularKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldCelular.getText());
            preenchertabela("select * from telefones where celular like '%" + jTextFieldCelular.getText() + "%'");
          
        }
    }//GEN-LAST:event_jTextFieldCelularKeyPressed

    private void jTableSolicitaçõesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableSolicitaçõesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSolicitaçõesKeyPressed

    private void jTableSolicitaçõesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSolicitaçõesMouseClicked
        // TODO add your handling code here:
         String id = ""+jTableSolicitações.getValueAt(jTableSolicitações.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from solicitacoes where id='"+ id +"'");
        
        try {
        conecta.rs.first();
        //jTextFieldId.setText(String.valueOf(conecta.rs.getInt("IdEntrevistas")));
        jTextFieldId.setText(String.valueOf(conecta.rs.getInt("id")));
        jTextFieldSolicitante.setText(conecta.rs.getString("solicitante"));
        jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
        jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
        jTextFieldCliente.setText(conecta.rs.getString("cliente"));
        jTextFieldTelefone.setText(conecta.rs.getString("telefone"));
        jTextFieldCelular.setText(conecta.rs.getString("celular"));
        jTextFieldTentativas.setText(conecta.rs.getString("tentativas"));
        jComboBoxExito.setSelectedItem(conecta.rs.getString("exito"));
        jTextFieldObservacao.setText(conecta.rs.getString("observacao"));
//        jTextFieldCargo.setText(conecta.rs.getString("Cargo"));   
//        jTextFieldUsuario.setText(conecta.rs.getString("Usuario")); 
//        jComboBoxCompareceu.setSelectedItem(conecta.rs.getString("Compareceu"));
//        jComboBoxCorrigiu.setSelectedItem(conecta.rs.getString("Corrigiu"));
//        jComboBoxRetorno.setSelectedItem(conecta.rs.getString("Retorno"));
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableSolicitaçõesMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if(jTextFieldSolicitante.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva um solicitante!");}
else{if(jComboBoxDepartamento.getSelectedItem().equals("Sem seleção")){JOptionPane.showMessageDialog(null,"Selecione um Departamento!");}
else{if(jTextFieldEmpresa.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva uma empresa!");}
else{if(jTextFieldCliente.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva um cliente!");}
else{if(jTextFieldTelefone.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva uma telefone!");}
else{if(jTextFieldCelular.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva um celular!");}
else{if(jTextFieldTentativas.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva uma tentativa!");}
else{if(jTextFieldObservacao.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva uma Observação!");}
else{

        try{
            conecta.conectaBanco();
        PreparedStatement pst = conecta.conn.prepareStatement("insert into solicitacoes (SOLICITANTE,DEPARTAMENTO,EMPRESA,CLIENTE,TELEFONE,CELULAR,TENTATIVAS,EXITO,OBSERVACAO,data,hora,usuario)values (?,?,?,?,?,?,?,?,?,?,?,?)");
        pst.setString(1,jTextFieldSolicitante.getText());
        pst.setString(2, (String) jComboBoxDepartamento.getSelectedItem());
        pst.setString(3,jTextFieldEmpresa.getText());
        pst.setString(4,jTextFieldCliente.getText());
        pst.setString(5,jTextFieldTelefone.getText());
        pst.setString(6,(String) jTextFieldCelular.getText());
        pst.setString(7,jTextFieldTentativas.getText());
        pst.setString(8, (String) jComboBoxExito.getSelectedItem());
        pst.setString(9,jTextFieldObservacao.getText());
        pst.setString(10,jLabelData.getText());
        pst.setString(11,jLabelHora.getText());
        pst.setString(12,jTextFieldUsario.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
        preenchertabelaa("select * from solicitacoes order by id");
        //preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
       conecta.desconecta();
        } catch (SQLException ex) {                        
            JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
        }
}
        }
        }
        }
}
        }
        }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update solicitacoes set solicitante= ?, departamento=?, empresa=?, cliente=?, telefone=?, celular=?, tentativas=?, exito=?, observacao=? where id=?");
            pst.setString(1,jTextFieldSolicitante.getText());
            pst.setString(2, (String) jComboBoxDepartamento.getSelectedItem());
            pst.setString(3,jTextFieldEmpresa.getText());
            pst.setString(4,jTextFieldCliente.getText());
            pst.setString(5,jTextFieldTelefone.getText());
            pst.setString(6,(String) jTextFieldCelular.getText());
            pst.setString(7,jTextFieldTentativas.getText());
            pst.setString(8, (String) jComboBoxExito.getSelectedItem());
            pst.setString(9,jTextFieldObservacao.getText());
            pst.setInt(10,Integer.parseInt(jTextFieldId.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            preenchertabelaa("select * from solicitacoes order by id");
        //    preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         jTextFieldId.setText("");
        jTextFieldSolicitante.setText("");
        jComboBoxDepartamento.setSelectedItem("Sem seleção");
        jTextFieldEmpresa.setText("");
        jTextFieldCliente.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldCelular.setText("");
        jTextFieldTentativas.setText("");
        jComboBoxExito.setSelectedItem("Com Sucessso Celular");
       // jTextField1log.setText("");
        jTextFieldObservacao.setText("");
        //preenchertabela("select * from usuarios order by id");
        preenchertabela("select * from telefones order by id");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextFieldCelular.setText("null");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextFieldTelefone.setText("null");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            if(jTextFieldTel.getText().equals("")){JOptionPane.showMessageDialog(null,"Descreva um Telefone!");}
else{
        try{
            conecta.conectaBanco();
        PreparedStatement pst = conecta.conn.prepareStatement("insert into telefones (empresa,cliente,telefone,celular,dados)values (?,?,?,?,?)");
        pst.setString(1,jTextFieldPessoa.getText());
        pst.setString(2,jTextFieldPessoaa.getText());
        pst.setString(3,jTextFieldTel.getText());
        pst.setString(4,jTextFieldCel.getText());
        pst.setString(5,jTextFieldDados.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
        preenchertabelaa("select * from telefones order by id");
        //preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
       conecta.desconecta();
        } catch (SQLException ex) {                        
            JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
        }
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldUsarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsarioActionPerformed
public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","EMPRESA","CLIENTE","TELEFONE","CELULAR","DADOS"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("empresa"),conecta.rs.getString("cliente"),conecta.rs.getString("telefone"),conecta.rs.getString("celular"),conecta.rs.getString("dados")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableTelefones.setModel(modelo);
        jTableTelefones.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableTelefones.getColumnModel().getColumn(0).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(1).setPreferredWidth(400);
        jTableTelefones.getColumnModel().getColumn(1).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(2).setPreferredWidth(220);
        jTableTelefones.getColumnModel().getColumn(2).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(3).setPreferredWidth(145);
        jTableTelefones.getColumnModel().getColumn(3).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(4).setPreferredWidth(145);
        jTableTelefones.getColumnModel().getColumn(4).setResizable(false);
        jTableTelefones.getColumnModel().getColumn(5).setPreferredWidth(750);
        jTableTelefones.getColumnModel().getColumn(5).setResizable(false);
        jTableTelefones.getTableHeader().setReorderingAllowed(true);
        jTableTelefones.setAutoResizeMode(jTableTelefones.AUTO_RESIZE_OFF);
        jTableTelefones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    
    
    public void preenchertabelaa(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","SOLICITANTE","DEPARTAMENTO","EMPRESA","CLIENTE","TELEFONE","CELULAR","TENTATIVAS","EXITO","OBSERVAÇÕES","DATA","HORA","USUARIO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("solicitante"),conecta.rs.getString("departamento"),conecta.rs.getString("empresa"),conecta.rs.getString("cliente"),conecta.rs.getString("telefone"),conecta.rs.getString("celular"),conecta.rs.getString("tentativas"),conecta.rs.getString("exito"),conecta.rs.getString("observacao"),conecta.rs.getString("data"),conecta.rs.getString("hora"),conecta.rs.getString("usuario")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe Solicitações cadastradas!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableSolicitações.setModel(modelo);
        jTableSolicitações.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableSolicitações.getColumnModel().getColumn(0).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableSolicitações.getColumnModel().getColumn(1).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTableSolicitações.getColumnModel().getColumn(2).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTableSolicitações.getColumnModel().getColumn(3).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableSolicitações.getColumnModel().getColumn(4).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(5).setPreferredWidth(85);
        jTableSolicitações.getColumnModel().getColumn(5).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(6).setPreferredWidth(85);
        jTableSolicitações.getColumnModel().getColumn(6).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(7).setPreferredWidth(110);
        jTableSolicitações.getColumnModel().getColumn(7).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(8).setPreferredWidth(130);
        jTableSolicitações.getColumnModel().getColumn(8).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(9).setPreferredWidth(400);
        jTableSolicitações.getColumnModel().getColumn(9).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTableSolicitações.getColumnModel().getColumn(10).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTableSolicitações.getColumnModel().getColumn(11).setResizable(false);
        jTableSolicitações.getColumnModel().getColumn(12).setPreferredWidth(85);
        jTableSolicitações.getColumnModel().getColumn(12).setResizable(false);
        jTableSolicitações.getTableHeader().setReorderingAllowed(true);
        jTableSolicitações.setAutoResizeMode(jTableSolicitações.AUTO_RESIZE_OFF);
        jTableSolicitações.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaLigacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxDepartamento;
    private javax.swing.JComboBox<String> jComboBoxExito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSolicitações;
    private javax.swing.JTable jTableTelefones;
    private javax.swing.JTextField jTextFieldCel;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldDados;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldObservacao;
    private javax.swing.JTextField jTextFieldPessoa;
    private javax.swing.JTextField jTextFieldPessoaa;
    private javax.swing.JTextField jTextFieldSolicitante;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldTentativas;
    private javax.swing.JTextField jTextFieldUsario;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe){
        jTextFieldUsario.setText(recebe);
    }   
}
