/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import modelo.ModeloLoginUsuario;
import javax.swing.JOptionPane;


/**
 *
 * @author vinicius
 */
public class CadastroDeUsuario extends javax.swing.JFrame {
    
    //ModeloLoginUsuario mod = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ConnectionConsulta conecta = new ConnectionConsulta();
    
    
    int flag=1;
    /**
     * Creates new form CadastroDeUsuario
     */
    public CadastroDeUsuario(String user) {
        initComponents();
        conecta.conectaBanco();
        jTextFieldLogin.setText(user);
    }
    
    CadastroDeUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldConfSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar senha");
        setUndecorated(true);

        jLabel1.setText("Alteração senha:");

        jLabel2.setText("Login:");

        jTextFieldLogin.setEnabled(false);
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmação de senha:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPasswordFieldSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPasswordFieldConfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(jButtonCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jPasswordFieldSenha)
                                .addComponent(jPasswordFieldConfSenha))
                            .addGap(38, 38, 38))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(372, 222));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
         
     if(jPasswordFieldSenha.getText().isEmpty()){
         JOptionPane.showMessageDialog(rootPane, "Preencha a senha para continuar! ");
         jPasswordFieldSenha.requestFocus();
    }else if(jPasswordFieldConfSenha.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Preencha a confirmação de senha para continuar! ");
        jPasswordFieldConfSenha.requestFocus();
    }else if(jPasswordFieldConfSenha.getText().length() < 8){
        JOptionPane.showMessageDialog(rootPane, "Digite uma senha maior que 7 digitos! ");
        jPasswordFieldConfSenha.requestFocus();
    }else
        
        if(jPasswordFieldSenha.getText().equals(jPasswordFieldConfSenha.getText())){
             
             
         if(flag == 1) {     
        //mod.setId(Integer.parseInt(jTextFieldCod.getText()));
//        modelo.setLogin(jTextFieldLogin.getText());
//        //mod.setNome(jTextFieldNome.getText());
//        modelo.setSenha(jPasswordFieldSenha.getText());                          
//        modelo.setSenha(jPasswordFieldConfSenha.getText());  
//        control.salvar(modelo);
//        //jTextFieldCod.setText("");
//        jTextFieldLogin.setText("");
//        //jTextFieldNome.setText("");
//        jPasswordFieldConfSenha.setText("");
//        jPasswordFieldSenha.setText("");
//        jButtonSalvar.setEnabled(!true);
//        jTextFieldLogin.setEnabled(!true);
//        //jTextFieldNome.setEnabled(!true);      
//        jPasswordFieldConfSenha.setEnabled(!true);        
//        jPasswordFieldSenha.setEnabled(!true);        
//        jButtonIniciar.setEnabled(!false);
//        jButtonCancelar.setEnabled(!true); 
//        jButtonEditar.setEnabled(false);
         try {
            PreparedStatement pst = conecta.conn.prepareStatement("update login set senha=? where login='"+jTextFieldLogin.getText()+"'");
            pst.setString(1,jPasswordFieldConfSenha.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
        } else{
             
              try {
            PreparedStatement pst = conecta.conn.prepareStatement("update login set senha=? where login='"+jTextFieldLogin.getText()+"'");
            pst.setString(1,jPasswordFieldConfSenha.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
        //mod.setId(Integer.parseInt(jTextFieldCod.getText()));
//        modelo.setLogin(jTextFieldLogin.getText());
//       // mod.setNome(jTextFieldNome.getText());
//        modelo.setSenha(jPasswordFieldSenha.getText());                          
//        modelo.setSenha(jPasswordFieldConfSenha.getText());  
//        control.alterar(modelo);
//        //jTextFieldCod.setText("");
//        jTextFieldLogin.setText("");
//        //jTextFieldNome.setText("");
//        jPasswordFieldConfSenha.setText("");
//        jPasswordFieldSenha.setText("");
//        jButtonSalvar.setEnabled(!true);
//        jTextFieldLogin.setEnabled(!true);
//        //jTextFieldNome.setEnabled(!true);      
//        jPasswordFieldConfSenha.setEnabled(!true);        
//        jPasswordFieldSenha.setEnabled(!true);        
//        jButtonIniciar.setEnabled(!false);
//        jButtonCancelar.setEnabled(!true); 
//        jButtonEditar.setEnabled(false);
         }
            
         }else{
         JOptionPane.showMessageDialog(rootPane, "As senhas não correspondem! ");
        }            

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
       // jTextFieldCod.setText("");
       // jTextFieldLogin.setText("");
       // jTextFieldNome.setText("");
//        jPasswordFieldConfSenha.setText("");
//        jPasswordFieldSenha.setText("");
//        jButtonSalvar.setEnabled(!true);
//        jTextFieldLogin.setEnabled(!true);
        //jTextFieldNome.setEnabled(!true);      
//        jPasswordFieldConfSenha.setEnabled(!true);        
//        jPasswordFieldSenha.setEnabled(!true);        
//        jButtonIniciar.setEnabled(!false);
//        jButtonCancelar.setEnabled(!true); 
//        jButtonEditar.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordFieldConfSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
