/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import controle.ControleLogin;
import controle.ControleLoginUsuario;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloLogin;
import modelo.ModeloLoginUsuario;
import modelo.ModeloTabela;

/**
 *
 * @author vinicius
 */
public class CadastroLogin extends javax.swing.JFrame {
    
    ModeloLogin mod = new ModeloLogin();
    ControleLogin control = new ControleLogin();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
  //  ControleLoginUsuario control = new ControleLoginUsuario();
    ConnectionConsulta conecta = new ConnectionConsulta();
    
    
    int flag=1;
    /**
     * Creates new form CadastroLogin
     */
    public CadastroLogin() {
        initComponents();
        preenchertabela("select * from login where permissao in ('Gestor', 'Recebedor', 'recepção') order by nome"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPermissao = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLogin = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDest1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxDest2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxDepart = new javax.swing.JComboBox<>();
        jPasswordFieldSenha1 = new javax.swing.JPasswordField();
        jPasswordFieldConfSenha1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxPermissao2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Cadastro de Login");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Código:");

        jTextFieldCod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmação de senha:");

        jLabel6.setText("Login:");

        jTextFieldLogin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldLogin.setEnabled(false);
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPrimeiro.setText("<<");
        jButtonPrimeiro.setEnabled(false);
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("<");
        jButtonAnterior.setEnabled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setText(">");
        jButtonProximo.setEnabled(false);
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setText(">>");
        jButtonUltimo.setEnabled(false);
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel7.setText("Permissão:");

        jComboBoxPermissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestor", "Recepção", "Recebedor", "Financeiro" }));
        jComboBoxPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPermissaoActionPerformed(evt);
            }
        });

        jTableLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLoginMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLogin);

        jLabel8.setText("Destinatario:");

        jComboBoxDest1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Adriana", "Andreia", "Bruno", "Edilene", "Gustavo", "GustavoC", "Jurídico", "Katia", "RH", "TDP", "Declarações", "Financeiro" }));

        jLabel9.setText("Destinatario2:");

        jComboBoxDest2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Adriana", "Andreia", "Bruno", "Edilene", "Gustavo", "GustavoC", "Jurídico", "Katia", "RH", "TDP", "Declarações", "Financeiro" }));

        jLabel10.setText("Departamento:");

        jComboBoxDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Contábil", "Fiscal", "Jurídico", "RH", "DP", "Declarações", "Financeiro" }));

        jPasswordFieldSenha1.setText("jPasswordField1");

        jPasswordFieldConfSenha1.setText("jPasswordField2");

        jLabel11.setText("Permissão2:");

        jComboBoxPermissao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Gestor", "Recepção", "Recebedor", "Financeiro" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxDest1, 0, 209, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPermissao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxPermissao2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jComboBoxDest2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addComponent(jComboBoxDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(jPasswordFieldSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)
                                .addComponent(jPasswordFieldConfSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonEditar)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonPrimeiro)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAnterior)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonProximo)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonUltimo)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSair)))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPermissao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jComboBoxDest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldConfSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSair)))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(925, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
//    flag=2;
//        jButtonSalvar.setEnabled(true);
//        jTextFieldLogin.setEnabled(true);
//        jTextFieldNome.setEnabled(true);      
//        jPasswordFieldConfSenha.setEnabled(true);        
//        jPasswordFieldSenha.setEnabled(true);        
//        jButtonNovo.setEnabled(false);
//        jButtonCancelar.setEnabled(true); 
//        jButtonEditar.setEnabled(false);
//        jButtonExcluir.setEnabled(false);
try {
     conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update login set nome= ?, permissao=?, permissao2=?, login=?, area=?, subarea=?, depart=?, senha=? where id_login=?");
            pst.setString(1,jTextFieldNome.getText());
            pst.setString(2, (String) jComboBoxPermissao.getSelectedItem());
            pst.setString(3, (String)jComboBoxPermissao2.getSelectedItem());
            pst.setString(4,jTextFieldLogin.getText());
            pst.setString(5, (String) jComboBoxDest1.getSelectedItem());
            pst.setString(6,(String) jComboBoxDest2.getSelectedItem());
            pst.setString(7,(String) jComboBoxDepart.getSelectedItem());
            pst.setString(8,jPasswordFieldSenha1.getText());
            pst.setInt(9,Integer.parseInt(jTextFieldCod.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            preenchertabela("select * from login order by nome");
            //preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
         conecta.desconecta();
         conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        mod = control.Ultimo();
        jTextFieldCod.setText(String.valueOf(mod.getId()));
        jTextFieldNome.setText(mod.getNome());
        jTextFieldLogin.setText(mod.getLogin());
        jComboBoxPermissao.setSelectedItem(mod.getPermissao());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true); 
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jTextFieldCod.setText("");
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldConfSenha1.setText("");
        jPasswordFieldSenha1.setText("");
        jButtonSalvar.setEnabled(true);
        jTextFieldLogin.setEnabled(true);
        jTextFieldNome.setEnabled(true);      
        jPasswordFieldConfSenha1.setEnabled(true);        
        jPasswordFieldSenha1.setEnabled(true);        
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);   
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCod.setText("");
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldConfSenha1.setText("");
        jPasswordFieldSenha1.setText("");
        jButtonSalvar.setEnabled(!true);
        jTextFieldLogin.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);      
        jPasswordFieldConfSenha1.setEnabled(!true);        
        jPasswordFieldSenha1.setEnabled(!true);        
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(!true); 
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if(flag == 1) {
        if(jPasswordFieldSenha1.getText().equals(jPasswordFieldConfSenha1.getText())){
        mod.setLogin(jTextFieldLogin.getText());
        mod.setNome(jTextFieldNome.getText());
        mod.setPermissao((String)jComboBoxPermissao.getSelectedItem());
        mod.setPermissao2((String)jComboBoxPermissao2.getSelectedItem());
        mod.setSenha(jPasswordFieldSenha1.getText());
        mod.setArea((String)jComboBoxDest1.getSelectedItem());
        mod.setSubarea((String)jComboBoxDest2.getSelectedItem());
        mod.setDepart((String)jComboBoxDepart.getSelectedItem());
        control.salvar(mod);
        jTextFieldCod.setText("");
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldConfSenha1.setText("");
        jPasswordFieldSenha1.setText("");
        jComboBoxDest1.setSelectedItem("Sem seleção");
        jComboBoxDest2.setSelectedItem("Sem seleção");
        jComboBoxDepart.setSelectedItem("Sem seleção");
        jButtonSalvar.setEnabled(!true);
        jTextFieldLogin.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);      
        jPasswordFieldConfSenha1.setEnabled(!true);        
        jPasswordFieldSenha1.setEnabled(!true);        
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(!true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "As senhas não correspondem! ");
        }
        }else {
        if(jPasswordFieldSenha1.getText().equals(jPasswordFieldConfSenha1.getText())){
        mod.setId(Integer.parseInt(jTextFieldCod.getText()));
        mod.setLogin(jTextFieldLogin.getText());
        mod.setNome(jTextFieldNome.getText());
        mod.setPermissao((String)jComboBoxPermissao.getSelectedItem());
        mod.setPermissao2((String)jComboBoxPermissao2.getSelectedItem());
        mod.setArea((String)jComboBoxDest1.getSelectedItem());
        mod.setSubarea((String)jComboBoxDest2.getSelectedItem());
        mod.setDepart((String)jComboBoxDepart.getSelectedItem());
        control.alterar(mod);
        jTextFieldCod.setText("");
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldConfSenha1.setText("");
        jPasswordFieldSenha1.setText("");
        jComboBoxDest1.setSelectedItem("Sem seleção");
        jComboBoxDest2.setSelectedItem("Sem seleção");
        jComboBoxDepart.setSelectedItem("Sem seleção");
        jButtonSalvar.setEnabled(!true);
        jTextFieldLogin.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);      
        jPasswordFieldConfSenha1.setEnabled(!true);        
        jPasswordFieldSenha1.setEnabled(!true);        
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(!true); 
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        flag = 1;
        } else {
            JOptionPane.showMessageDialog(rootPane, "As senhas não correspondem! ");
        }
                }
        preenchertabela("select * from login order by nome");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        mod = control.Primeiro();
        jTextFieldCod.setText(String.valueOf(mod.getId()));
        jTextFieldNome.setText(mod.getNome());
        jTextFieldLogin.setText(mod.getLogin());
        jComboBoxPermissao.setSelectedItem(mod.getPermissao());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true); 
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        mod = control.Anterior();
        jTextFieldCod.setText(String.valueOf(mod.getId()));
        jTextFieldNome.setText(mod.getNome());
        jTextFieldLogin.setText(mod.getLogin());
        jComboBoxPermissao.setSelectedItem(mod.getPermissao());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true); 
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        mod = control.Proximo();
        jTextFieldCod.setText(String.valueOf(mod.getId()));
        jTextFieldNome.setText(mod.getNome());
        jTextFieldLogin.setText(mod.getLogin());
        jComboBoxPermissao.setSelectedItem(mod.getPermissao());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jComboBoxPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPermissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPermissaoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        mod.setId(Integer.parseInt(jTextFieldCod.getText()));
        mod.setLogin(jTextFieldLogin.getText());
        mod.setNome(jTextFieldNome.getText());
        mod.setPermissao((String)jComboBoxPermissao.getSelectedItem());
        mod.setPermissao((String)jComboBoxPermissao2.getSelectedItem());
        mod.setPermissao((String)jComboBoxDest1.getSelectedItem());
        mod.setPermissao((String)jComboBoxDest2.getSelectedItem());
        mod.setPermissao((String)jComboBoxDepart.getSelectedItem());
        control.excluir(mod);
        jTextFieldCod.setText("");
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldConfSenha1.setText("");
        jPasswordFieldSenha1.setText("");
        jButtonSalvar.setEnabled(!true);
        jTextFieldLogin.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);      
        jPasswordFieldConfSenha1.setEnabled(!true);        
        jPasswordFieldSenha1.setEnabled(!true);        
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(!true); 
        preenchertabela("select * from login order by nome");
        conecta.desconecta();

        //jButtonEditar.setEnabled(false);
        //jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTableLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLoginMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableLogin.getValueAt(jTableLogin.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from login where id_login='"+ id +"'");
        
        try {
        conecta.rs.first();
        jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id_login")));
        jTextFieldNome.setText(conecta.rs.getString("nome"));
        jComboBoxPermissao.setSelectedItem(conecta.rs.getString("permissao"));
        jComboBoxPermissao2.setSelectedItem(conecta.rs.getString("permissao2"));
        jTextFieldLogin.setText(conecta.rs.getString("login"));
        jPasswordFieldSenha1.setText(conecta.rs.getString("senha"));
        jComboBoxDest1.setSelectedItem(conecta.rs.getString("area"));
        jComboBoxDest2.setSelectedItem(conecta.rs.getString("subarea"));
        jComboBoxDepart.setSelectedItem(conecta.rs.getString("depart"));
//        jButtonAlterar.setEnabled(true);
        //jButtonExcluir.setEnabled(false);
//        jTextFieldEmpresa.setEnabled(true);
//        jTextFieldDescricao.setEnabled(true);
//        jComboBoxDestinatario.setEnabled(true);
//        jComboBoxDepartamento.setEnabled(true);
//        jTextFieldData.setEnabled(false);
//        jTextFieldDataEntrega.setEnabled(false);
//        jTextFieldHorario.setEnabled(false);
//        jComboBoxEntrega.setEnabled(true);
//        jComboBoxCorreios.setEnabled(true);
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableLoginMouseClicked
    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","NOME","PERMISSAO","PERMISSAO2","LOGIN","DESTINATARIO","DESTINATARIO2","DEPARTAMENTO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
          //  conecta.conectaBanco();
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("id_login"),conecta.rs.getString("nome"),conecta.rs.getString("permissao"),conecta.rs.getString("permissao2"),conecta.rs.getString("login"),conecta.rs.getString("area"),conecta.rs.getString("subarea"),conecta.rs.getString("depart")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
       //     JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableLogin.setModel(modelo);
        jTableLogin.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableLogin.getColumnModel().getColumn(0).setResizable(false);
        jTableLogin.getColumnModel().getColumn(1).setPreferredWidth(190);
        jTableLogin.getColumnModel().getColumn(1).setResizable(false);
        jTableLogin.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableLogin.getColumnModel().getColumn(2).setResizable(false);
        jTableLogin.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableLogin.getColumnModel().getColumn(3).setResizable(false);
        jTableLogin.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableLogin.getColumnModel().getColumn(4).setResizable(false);
        jTableLogin.getColumnModel().getColumn(5).setPreferredWidth(105);
        jTableLogin.getColumnModel().getColumn(5).setResizable(false);
        jTableLogin.getColumnModel().getColumn(6).setPreferredWidth(115);
        jTableLogin.getColumnModel().getColumn(6).setResizable(false);
        jTableLogin.getColumnModel().getColumn(7).setPreferredWidth(115);
        jTableLogin.getColumnModel().getColumn(7).setResizable(false);
        jTableLogin.getTableHeader().setReorderingAllowed(true);
        jTableLogin.setAutoResizeMode(jTableLogin.AUTO_RESIZE_OFF);
        jTableLogin.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JComboBox<String> jComboBoxDepart;
    private javax.swing.JComboBox<String> jComboBoxDest1;
    private javax.swing.JComboBox<String> jComboBoxDest2;
    private javax.swing.JComboBox<String> jComboBoxPermissao;
    private javax.swing.JComboBox<String> jComboBoxPermissao2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfSenha1;
    private javax.swing.JPasswordField jPasswordFieldSenha1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLogin;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
