/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mxrck.autocompleter.TextAutoCompleter;
import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import controle.conectar;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerDateModel;
import modelo.ModeloLoginUsuario;
import modelo.ModeloTabela;
import modelo.Usuario;

/**
 *
 * @author vinicius
 */
public class CancelaReuniao extends javax.swing.JFrame {

     ConnectionConsulta conecta = new ConnectionConsulta();
    Usuario mod = new Usuario();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();
    CancelaReuniao enviasenha;
    /**
     * Creates new form CancelaReuniao
     */
    public CancelaReuniao() {
        initComponents();
        items();
        itemms();
        conecta.conectaBanco();
       // preenchertabela("select * from reuniao order by idreuniao");
       //preenchertabela("select * from reuniao where solicitante ='Andréia' and STR_TO_DATE(datainicio, '%d/%m/%Y') order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
       
    }

    public void items (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldEvento);
        
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT evento from reuniao"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("evento"));
            }
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }
    
    public void itemms (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter(jTextFieldCliente);
        
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT cliente from reuniao"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("cliente"));
            }
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }

        public void itemm (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldSolicitante);
        
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT solicitante from reuniao"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("solicitante"));
            }
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEvento = new javax.swing.JTextField();
        jComboBoxLocal = new javax.swing.JComboBox<>();
        jComboBoxPessoas = new javax.swing.JComboBox<>();
        jTextFieldSolicitante = new javax.swing.JTextField();
        jTextFieldCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReuniao = new javax.swing.JTable();
        jTextFieldId = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextFieldDataInicio = new javax.swing.JTextField();
        jTextFieldInicio = new javax.swing.JTextField();
        jTextFieldTermino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JtextUser = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Sala Grande", "Sala Média", "Sala Pequena" }));

        jComboBoxPessoas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Todos", "Parcial", "Cliente" }));

        jTextFieldSolicitante.setEnabled(false);

        jTableReuniao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableReuniao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReuniaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableReuniao);

        jTextFieldId.setEnabled(false);

        jButtonAlterar.setText("Editar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Evento:");

        jLabel3.setText("Data Inicio:");

        jLabel4.setText("Horario Inicio:");

        jLabel5.setText("Horario termino:");

        jLabel6.setText("Local:");

        jLabel7.setText("Participantes:");

        jLabel8.setText("Solicitante:");

        jLabel9.setText("Cliente:");

        jLabel10.setText("Pesquisa por data:");

        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Alteração Reuniao:");

        jLabel12.setText("Usuario:");

        JtextUser.setEnabled(false);

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(JtextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButton3)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonIniciar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("update reuniao set evento= ?, datainicio=?, horarioinicio=?, horariotermino=?,local=?, participantes=?, solicitante=?, cliente=? where idreuniao=?");
            pst.setString(1,jTextFieldEvento.getText());
            pst.setString(2,jTextFieldDataInicio.getText());
            pst.setString(3, (String) jTextFieldInicio.getText());
            pst.setString(4, (String) jTextFieldTermino.getText());
            pst.setString(5, (String) jComboBoxLocal.getSelectedItem());
            pst.setString(6, (String) jComboBoxPessoas.getSelectedItem());
            pst.setString(7,jTextFieldSolicitante.getText());
            pst.setString(8,jTextFieldCliente.getText());
            pst.setInt(9,Integer.parseInt(jTextFieldId.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso!");
            preenchertabela("select * from reuniao where solicitante ='Andréia' and STR_TO_DATE(datainicio, '%d/%m/%Y') order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableReuniaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReuniaoMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableReuniao.getValueAt(jTableReuniao.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from reuniao where idreuniao='"+ id +"'");
        
        try {
        conecta.rs.first();
        jTextFieldId.setText(String.valueOf(conecta.rs.getInt("idreuniao")));
        jTextFieldEvento.setText(conecta.rs.getString("evento"));
        jTextFieldDataInicio.setText((conecta.rs.getString("datainicio")));
        jTextFieldInicio.setText(conecta.rs.getString("horarioinicio"));
        jTextFieldTermino.setText(conecta.rs.getString("horariotermino"));
        jComboBoxLocal.setSelectedItem(conecta.rs.getString("local"));
        jComboBoxPessoas.setSelectedItem(conecta.rs.getString("participantes"));
        jTextFieldSolicitante.setText(conecta.rs.getString("solicitante"));
        jTextFieldCliente.setText(conecta.rs.getString("cliente"));   
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldId.setEnabled(false);
        jTextFieldEvento.setEnabled(true);
        jTextFieldDataInicio.setEnabled(true);
        jTextFieldInicio.setEnabled(true);
        jTextFieldTermino.setEnabled(true);
        jComboBoxLocal.setEnabled(true);
        jComboBoxPessoas.setEnabled(true);
        jTextFieldSolicitante.setEnabled(true);
        jTextFieldCliente.setEnabled(true);
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableReuniaoMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("delete from reuniao where idreuniao= ?");
            pst.setString(1,jTextFieldId.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso!");
            preenchertabela("select * from reuniao where solicitante ='Andréia' and STR_TO_DATE(datainicio, '%d/%m/%Y') order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao excluir!\n Erro: "+ex);
        }
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldId.setEnabled(false);
        jTextFieldEvento.setEnabled(true);
        jTextFieldDataInicio.setEnabled(true);
        jTextFieldInicio.setEnabled(true);
        jTextFieldTermino.setEnabled(true);
        jComboBoxLocal.setEnabled(true);
        jComboBoxPessoas.setEnabled(true);
        jTextFieldSolicitante.setEnabled(true);
        jTextFieldCliente.setEnabled(true);
        jTextFieldId.setText("");
        jTextFieldEvento.setText("");
        jTextFieldDataInicio.setText("");
        jTextFieldInicio.setText("");
        jTextFieldTermino.setText("");
        jComboBoxLocal.setSelectedItem("Sem seleção");
        jComboBoxPessoas.setSelectedItem("Sem seleção");
        jTextFieldSolicitante.setText("");
        jTextFieldCliente.setText("");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            mod.setPesquisa(jTextFieldPesquisa.getText());     
            preenchertabela("select reuniao.* from reuniao INNER JOIN login on reuniao.solicitante = login.login where login = '" + JtextUser.getText()+"' and datainicio like '%" + jTextFieldPesquisa.getText() + "%'");
        }     
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldEvento.setText("");
        jTextFieldDataInicio.setText("");
        jTextFieldInicio.setText("");
        jTextFieldTermino.setText("");
        jTextFieldCliente.setText("");
        jTextFieldPesquisa.setText("");
        jComboBoxLocal.setSelectedItem("Sem seleção");
        jComboBoxPessoas.setSelectedItem("Sem seleção");
       // preenchertabela("select * from reuniao where solicitante ='Andréia' and STR_TO_DATE(datainicio, '%d/%m/%Y') order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
       preenchertabela("select reuniao.* from reuniao INNER JOIN login on reuniao.solicitante = login.login where login = '" + JtextUser.getText()+"' and STR_TO_DATE(datainicio, '%d/%m/%Y') order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
        preenchertabela("select reuniao.* from reuniao INNER JOIN login on reuniao.solicitante = login.login where login = '" + JtextUser.getText()+"' and STR_TO_DATE(datainicio, '%d/%m/%Y') order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    
     public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","EVENTO","LOCAL","DATAINI","hrsI","hrsT","PARTICIPANTES","SOLICITANTE","CLIENTE"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("idreuniao"),conecta.rs.getString("evento"),conecta.rs.getString("local"),conecta.rs.getString("datainicio"),conecta.rs.getString("horarioinicio"),conecta.rs.getString("horariotermino"),conecta.rs.getString("participantes"),conecta.rs.getString("solicitante"),conecta.rs.getString("cliente")});
        }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Pesquisa inexistente!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableReuniao.setModel(modelo);
        jTableReuniao.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableReuniao.getColumnModel().getColumn(0).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(1).setPreferredWidth(175);
        jTableReuniao.getColumnModel().getColumn(1).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableReuniao.getColumnModel().getColumn(2).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTableReuniao.getColumnModel().getColumn(3).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTableReuniao.getColumnModel().getColumn(4).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableReuniao.getColumnModel().getColumn(5).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(6).setPreferredWidth(110);
        jTableReuniao.getColumnModel().getColumn(6).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(7).setPreferredWidth(165);
        jTableReuniao.getColumnModel().getColumn(7).setResizable(false);
        jTableReuniao.getColumnModel().getColumn(8).setPreferredWidth(195);
        jTableReuniao.getColumnModel().getColumn(8).setResizable(false);
        jTableReuniao.getTableHeader().setReorderingAllowed(true);
        jTableReuniao.setAutoResizeMode(jTableReuniao.AUTO_RESIZE_OFF);
        jTableReuniao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelaReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelaReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelaReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelaReuniao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelaReuniao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextUser;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxLocal;
    private javax.swing.JComboBox<String> jComboBoxPessoas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReuniao;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldDataInicio;
    private javax.swing.JTextField jTextFieldEvento;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldInicio;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldSolicitante;
    private javax.swing.JTextField jTextFieldTermino;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe){
        JtextUser.setText(recebe);
    }   
}
