/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import java.awt.Desktop;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloLoginUsuario;
import modelo.ModeloTabela;
import modelo.Usuario;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author vinicius
 */
public class ConsultaLigacoes extends javax.swing.JFrame {
    
   private final String ruta = System.getProperties().getProperty("user.dir");
   ConnectionConsulta conecta = new ConnectionConsulta();
    Usuario mod = new Usuario();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();
    /**
     * Creates new form ConsultaLigacoes
     */
    public ConsultaLigacoes() {
        initComponents();
        this.setExtendedState(this.getExtendedState()|VisualizadorProfissionais.MAXIMIZED_BOTH);
        conecta.conectaBanco();
        preenchertabela("select * from solicitacoes order by id");
        jTableSolicitacoes.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSolicitacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSolicitante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldExito = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldobservacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUserr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableSolicitacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableSolicitacoes);

        jLabel1.setText("Solicitante");

        jTextFieldSolicitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSolicitanteKeyPressed(evt);
            }
        });

        jLabel2.setText("Cliente/Pessoa:");

        jTextFieldCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldClienteKeyPressed(evt);
            }
        });

        jButton1.setText("Criar Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Departamento:");

        jTextFieldDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDepartamentoKeyPressed(evt);
            }
        });

        jLabel4.setText("Empresa/Pessoa:");

        jTextFieldEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmpresaKeyPressed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        jTextFieldTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefoneKeyPressed(evt);
            }
        });

        jLabel6.setText("Celular/Telefone:");

        jTextFieldCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCelularKeyPressed(evt);
            }
        });

        jLabel7.setText("Êxito:");

        jTextFieldExito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldExitoKeyPressed(evt);
            }
        });

        jLabel8.setText("Observação:");

        jTextFieldobservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldobservacaoKeyPressed(evt);
            }
        });

        jLabel9.setText("Usuário:");

        jTextFieldUserr.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEmpresa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(19, 19, 19)
                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldExito, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 710, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldobservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserr, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldUserr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldExito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldobservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSolicitanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSolicitanteKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldSolicitante.getText());
            preenchertabela("select * from solicitacoes where solicitante like '%" + jTextFieldSolicitante.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldSolicitanteKeyPressed

    private void jTextFieldDepartamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDepartamentoKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldDepartamento.getText());
            preenchertabela("select * from solicitacoes where departamento like '%" + jTextFieldDepartamento.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldDepartamentoKeyPressed

    private void jTextFieldEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmpresaKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldEmpresa.getText());
            preenchertabela("select * from solicitacoes where departamento like '%" + jTextFieldEmpresa.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldEmpresaKeyPressed

    private void jTextFieldClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClienteKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldCliente.getText());
            preenchertabela("select * from solicitacoes where cliente like '%" + jTextFieldCliente.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldClienteKeyPressed

    private void jTextFieldTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldTelefone.getText());
            preenchertabela("select * from solicitacoes where telefone like '%" + jTextFieldTelefone.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldTelefoneKeyPressed

    private void jTextFieldCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCelularKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldCelular.getText());
            preenchertabela("select * from solicitacoes where celular like '%" + jTextFieldCelular.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldCelularKeyPressed

    private void jTextFieldExitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExitoKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldExito.getText());
            preenchertabela("select * from solicitacoes where exito like '%" + jTextFieldExito.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldExitoKeyPressed

    private void jTextFieldobservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldobservacaoKeyPressed
        // TODO add your handling code here:
             if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldobservacao.getText());
            preenchertabela("select * from solicitacoes where observacao like '%" + jTextFieldobservacao.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldobservacaoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try{

            Thread t = new Thread(){
                public void run(){
                    XSSFWorkbook workbook = new XSSFWorkbook();
                    XSSFSheet hoja = workbook.createSheet();

                    XSSFRow fila = hoja.createRow(0);
                    fila.createCell(0).setCellValue("ID");
                    fila.createCell(1).setCellValue("SOLICITANTE");
                    fila.createCell(2).setCellValue("DEPARTAMENTO");
                    fila.createCell(3).setCellValue("EMPRESA");
                    fila.createCell(4).setCellValue("CLIENTE");
                    fila.createCell(5).setCellValue("TELEFONE");
                    fila.createCell(6).setCellValue("CELULAR");
                    fila.createCell(7).setCellValue("TENTATIVAS");
                    fila.createCell(8).setCellValue("EXITO");
                    fila.createCell(9).setCellValue("OBSERVAÇÕES");
                    fila.createCell(10).setCellValue("DATA");
                    fila.createCell(11).setCellValue("HORA");
                    fila.createCell(12).setCellValue("USUARIO");
                    jProgressBar1.setMaximum(jTableSolicitacoes.getRowCount());
                    XSSFRow filas;
                    Rectangle rect;
                    for(int i=0; i<jTableSolicitacoes.getRowCount(); i++){

                        rect = jTableSolicitacoes.getCellRect(i, 0, true);
                        try{
                            jTableSolicitacoes.scrollRectToVisible(rect);
                        }catch(java.lang.ClassCastException e){}
                        jTableSolicitacoes.setRowSelectionInterval(i, i);
                        jProgressBar1.setValue((i+1));

                        filas = hoja.createRow((i+1));
                        filas.createCell(0).setCellValue(jTableSolicitacoes.getValueAt(i, 0).toString());
                        filas.createCell(1).setCellValue(jTableSolicitacoes.getValueAt(i, 1).toString());
                        filas.createCell(2).setCellValue(jTableSolicitacoes.getValueAt(i, 2).toString());
                        filas.createCell(3).setCellValue(jTableSolicitacoes.getValueAt(i, 3).toString());
                        filas.createCell(4).setCellValue(jTableSolicitacoes.getValueAt(i, 4).toString());
                        filas.createCell(5).setCellValue(jTableSolicitacoes.getValueAt(i, 5).toString());
                        filas.createCell(6).setCellValue(jTableSolicitacoes.getValueAt(i, 6).toString());
                        filas.createCell(7).setCellValue(jTableSolicitacoes.getValueAt(i, 7).toString());
                        filas.createCell(8).setCellValue(jTableSolicitacoes.getValueAt(i, 8).toString());
                        filas.createCell(9).setCellValue(jTableSolicitacoes.getValueAt(i, 9).toString());
                        filas.createCell(10).setCellValue(jTableSolicitacoes.getValueAt(i, 10).toString());
                        filas.createCell(11).setCellValue(jTableSolicitacoes.getValueAt(i, 11).toString());
                        filas.createCell(12).setCellValue(jTableSolicitacoes.getValueAt(i, 12).toString());
                        // try{
                            //           Thread.sleep(20);
                            //      } catch (InterruptedException ex){
                            //         Logger.getLogger(Visualizador.class.getName ()).log(Level.SEVERE, null, ex);
                            //     }
                    }
                    jProgressBar1.setValue(0);
                    //jProgressBar1.setString("Abrindo Excel...");
                    //this.dispose();
                    //dispose();
                    try{
                        workbook.write(new FileOutputStream(new File(ruta+"//Excel.xlsx")));
                        Desktop.getDesktop().open(new File(ruta+"//Excel.xlsx"));
                    } catch (Exception ex) {
                        Logger.getLogger(VisualizadorProfissionais.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            t.start();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","SOLICITANTE","DEPARTAMENTO","EMPRESA","CLIENTE","TELEFONE","CELULAR","TENTATIVAS","EXITO","OBSERVAÇÕES","DATA","HORA","USUARIO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("solicitante"),conecta.rs.getString("departamento"),conecta.rs.getString("empresa"),conecta.rs.getString("cliente"),conecta.rs.getString("telefone"),conecta.rs.getString("celular"),conecta.rs.getString("tentativas"),conecta.rs.getString("exito"),conecta.rs.getString("observacao"),conecta.rs.getString("data"),conecta.rs.getString("hora"),conecta.rs.getString("usuario")});
        }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe Solicitações cadastradas!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableSolicitacoes.setModel(modelo);
        jTableSolicitacoes.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableSolicitacoes.getColumnModel().getColumn(0).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableSolicitacoes.getColumnModel().getColumn(1).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTableSolicitacoes.getColumnModel().getColumn(2).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTableSolicitacoes.getColumnModel().getColumn(3).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTableSolicitacoes.getColumnModel().getColumn(4).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableSolicitacoes.getColumnModel().getColumn(5).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTableSolicitacoes.getColumnModel().getColumn(6).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(7).setPreferredWidth(110);
        jTableSolicitacoes.getColumnModel().getColumn(7).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(8).setPreferredWidth(155);
        jTableSolicitacoes.getColumnModel().getColumn(8).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(9).setPreferredWidth(400);
        jTableSolicitacoes.getColumnModel().getColumn(9).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTableSolicitacoes.getColumnModel().getColumn(10).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTableSolicitacoes.getColumnModel().getColumn(11).setResizable(false);
        jTableSolicitacoes.getColumnModel().getColumn(12).setPreferredWidth(85);
        jTableSolicitacoes.getColumnModel().getColumn(12).setResizable(false);
        jTableSolicitacoes.getTableHeader().setReorderingAllowed(true);
        jTableSolicitacoes.setAutoResizeMode(jTableSolicitacoes.AUTO_RESIZE_OFF);
        jTableSolicitacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaLigacoes().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSolicitacoes;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldExito;
    private javax.swing.JTextField jTextFieldSolicitante;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldUserr;
    private javax.swing.JTextField jTextFieldobservacao;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe){
        jTextFieldUserr.setText(recebe);
    }   
}
