/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRXmlDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vinicius
 */
public class LeitorXml extends javax.swing.JFrame {

    /**
     * Creates new form LeitorXml
     */
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos xml","xml");
    public LeitorXml() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtRota = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuSub = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtRota.setEditable(false);

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenu3.setText("Abrir");

        MenuSub.setText("Selecionar Arquivo");
        MenuSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSubActionPerformed(evt);
            }
        });
        jMenu3.add(MenuSub);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TxtRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        JFileChooser filechoose = new JFileChooser();
        
        int opcao = filechoose.showOpenDialog(this);
        if(opcao==JFileChooser.APPROVE_OPTION){
            String nome_arquivo = filechoose.getSelectedFile().getPath();
            
            String rota = filechoose.getSelectedFile().toString();
                      
        }
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MenuSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSubActionPerformed
        // TODO add your handling code here:
          JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcao = filechoose.showOpenDialog(this);
        if(opcao==JFileChooser.APPROVE_OPTION){
          //  String nome_arquivo = filechoose.getSelectedFile().getPath();
            
            String rota = filechoose.getSelectedFile().toString();
            
            TxtRota.setText(rota);
            
              {    
        try {    
            ImageIcon imagemTituloJanela = new ImageIcon("\\\\hp2011\\e\\Citrix\\Dados NFE\\nfe.gif");                 
                //Caminho do arquivo .JASPER    
                String relatorio = ("\\\\hp2011\\e\\Citrix\\Dados NFE\\Danfe.jasper");    
                //Configurando a classe JRXmlDataSource que apontara o caminho do  nosso XML de dados e sua pesquisa XPath geral    
                JRXmlDataSource xml = new JRXmlDataSource(""+TxtRota.getText()+"", "/nfeProc/NFe/infNFe/det");    
                HashMap mapa = new HashMap();  
                mapa.put("Logo","\\\\hp2011\\e\\Citrix\\Dados NFE\\nfe.gif");  
                //Gerando o relatorio (Filling) informando o caminho do relatorio, os parametros (neste caso nenhum paramentro esta sendo passado ao relatorio, por isso o HashMap esta vazio) e o objeto JRXmlDataSource configurado)    
                JasperPrint jp = JasperFillManager.fillReport(relatorio, mapa, xml);     
                //Utilizando o JasperView, uma classe desktop do jasper para visualização dos relatorios    
                JasperViewer jv = new JasperViewer(jp, false);    
                jv.setTitle("VISUALIZADOR DE DOCUMENTO FISCAL ELETRÔNICA");  
                jv.setIconImage(imagemTituloJanela.getImage());  
                jv.setVisible(true);   
              //  exportando arquivo para pdf  
              // JasperExportManager.exportReportToPdfFile(jp, "C:/NFe/arquivo.pdf");  
               // Runtime.getRuntime().exec("cmd /c start C:/NFe/arquivo.pdf");  
               // deletando arquivo  
               //File file = new File("C:/NFe/arquivo.pdf");  
               //file.deleteOnExit();  
        } catch (JRException e) {    
            e.printStackTrace();    
        }    
    }   
            
        }
    }//GEN-LAST:event_MenuSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeitorXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeitorXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeitorXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeitorXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeitorXml().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuSub;
    private javax.swing.JTextField TxtRota;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
