/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vinicius
 */
public class Menu extends javax.swing.JFrame {
    Consultador enviatexto;
    ConfirmacaoRecebimento enviarecebimento;
    AgendarReuniao enviareuniao;
    EnvioEmail enviaEmail;
    AgendaEntrevistas agendaentre;
    EntrevistaFinaliza finalizaentre;
    AgendaLigacoes ligacaofinal;
    CancelaReuniao enviasenha;
    NovoTesteJanela recebesenhaa;
    ConsultaLigacoes recebeauto;
    AgendaTelefonica recebeautoo;
    ConnectionConsulta conecta = new ConnectionConsulta();
    /**
     * Creates new form Menu
     */
    public Menu(String user) {
        initComponents();
        //conecta.conectaBanco();
        jLabelUser.setText(user);
        this.setExtendedState(this.getExtendedState()|Menu.MAXIMIZED_BOTH);
        setIcon();
    }

    Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrarGrande = new javax.swing.JButton();
        jButtonVisualizarGrande = new javax.swing.JButton();
        jButtonCadastroUsuarioGrande = new javax.swing.JButton();
        jButtonRecebimentosGrande = new javax.swing.JButton();
        jButtonSairGrande = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCadastroUsuarioGrande1 = new javax.swing.JButton();
        jButtonCadastroUsuarioGrande2 = new javax.swing.JButton();
        jButtonCadastroUsuarioGrande3 = new javax.swing.JButton();
        jButtonVisualizarGrande1 = new javax.swing.JButton();
        jButtonVisualizarGrande2 = new javax.swing.JButton();
        jButtonVisualizarGrande3 = new javax.swing.JButton();
        jButtonVisualizarGrande4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonVisualizarProjetos = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Visualizar = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Visualizador = new javax.swing.JMenuItem();
        CadastroUsuario = new javax.swing.JMenuItem();
        Recebimento = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Olá:");

        jButtonCadastrarGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user medio.png"))); // NOI18N
        jButtonCadastrarGrande.setBorder(null);
        jButtonCadastrarGrande.setBorderPainted(false);
        jButtonCadastrarGrande.setContentAreaFilled(false);
        jButtonCadastrarGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrarGrande.setFocusPainted(false);
        jButtonCadastrarGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user grande user.png"))); // NOI18N
        jButtonCadastrarGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user grande user.png"))); // NOI18N
        jButtonCadastrarGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarGrandeActionPerformed(evt);
            }
        });

        jButtonVisualizarGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search1.png"))); // NOI18N
        jButtonVisualizarGrande.setContentAreaFilled(false);
        jButtonVisualizarGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search grande.png"))); // NOI18N
        jButtonVisualizarGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search grande.png"))); // NOI18N
        jButtonVisualizarGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrandeActionPerformed(evt);
            }
        });

        jButtonCadastroUsuarioGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list pequeno.png"))); // NOI18N
        jButtonCadastroUsuarioGrande.setBorder(null);
        jButtonCadastroUsuarioGrande.setBorderPainted(false);
        jButtonCadastroUsuarioGrande.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande.setEnabled(false);
        jButtonCadastroUsuarioGrande.setFocusPainted(false);
        jButtonCadastroUsuarioGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list  grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list  grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrandeActionPerformed(evt);
            }
        });

        jButtonRecebimentosGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder1.png"))); // NOI18N
        jButtonRecebimentosGrande.setBorder(null);
        jButtonRecebimentosGrande.setBorderPainted(false);
        jButtonRecebimentosGrande.setContentAreaFilled(false);
        jButtonRecebimentosGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRecebimentosGrande.setEnabled(false);
        jButtonRecebimentosGrande.setFocusPainted(false);
        jButtonRecebimentosGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder grande.png"))); // NOI18N
        jButtonRecebimentosGrande.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder grande.png"))); // NOI18N
        jButtonRecebimentosGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecebimentosGrandeActionPerformed(evt);
            }
        });

        jButtonSairGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close1.png"))); // NOI18N
        jButtonSairGrande.setBorder(null);
        jButtonSairGrande.setBorderPainted(false);
        jButtonSairGrande.setContentAreaFilled(false);
        jButtonSairGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSairGrande.setFocusPainted(false);
        jButtonSairGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close grande.png"))); // NOI18N
        jButtonSairGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close grande.png"))); // NOI18N
        jButtonSairGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairGrandeActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_botao.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_grande.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_grande.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Receber documento");

        jLabel3.setText("Cadastrar Profissionais");

        jLabel4.setText("Visualizar Profissionais");

        jButtonCadastroUsuarioGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio.png"))); // NOI18N
        jButtonCadastroUsuarioGrande1.setBorder(null);
        jButtonCadastroUsuarioGrande1.setBorderPainted(false);
        jButtonCadastroUsuarioGrande1.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande1.setEnabled(false);
        jButtonCadastroUsuarioGrande1.setFocusPainted(false);
        jButtonCadastroUsuarioGrande1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar Grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar Grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande1ActionPerformed(evt);
            }
        });

        jButtonCadastroUsuarioGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio cancel.png"))); // NOI18N
        jButtonCadastroUsuarioGrande2.setBorder(null);
        jButtonCadastroUsuarioGrande2.setBorderPainted(false);
        jButtonCadastroUsuarioGrande2.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande2.setEnabled(false);
        jButtonCadastroUsuarioGrande2.setFocusPainted(false);
        jButtonCadastroUsuarioGrande2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar grande cancel.png"))); // NOI18N
        jButtonCadastroUsuarioGrande2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar grande cancel.png"))); // NOI18N
        jButtonCadastroUsuarioGrande2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande2ActionPerformed(evt);
            }
        });

        jButtonCadastroUsuarioGrande3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio consulta.png"))); // NOI18N
        jButtonCadastroUsuarioGrande3.setBorder(null);
        jButtonCadastroUsuarioGrande3.setBorderPainted(false);
        jButtonCadastroUsuarioGrande3.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande3.setEnabled(false);
        jButtonCadastroUsuarioGrande3.setFocusPainted(false);
        jButtonCadastroUsuarioGrande3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar pesquisa grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar pesquisa grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande3ActionPerformed(evt);
            }
        });

        jButtonVisualizarGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user medio.png"))); // NOI18N
        jButtonVisualizarGrande1.setContentAreaFilled(false);
        jButtonVisualizarGrande1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande1.setEnabled(false);
        jButtonVisualizarGrande1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user grande user.png"))); // NOI18N
        jButtonVisualizarGrande1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user grande user.png"))); // NOI18N
        jButtonVisualizarGrande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande1ActionPerformed(evt);
            }
        });

        jButtonVisualizarGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio.png"))); // NOI18N
        jButtonVisualizarGrande2.setContentAreaFilled(false);
        jButtonVisualizarGrande2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar Grande.png"))); // NOI18N
        jButtonVisualizarGrande2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar Grande.png"))); // NOI18N
        jButtonVisualizarGrande2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande2ActionPerformed(evt);
            }
        });

        jButtonVisualizarGrande3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call Registro.png"))); // NOI18N
        jButtonVisualizarGrande3.setContentAreaFilled(false);
        jButtonVisualizarGrande3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande3.setEnabled(false);
        jButtonVisualizarGrande3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call Consultar.png"))); // NOI18N
        jButtonVisualizarGrande3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call Consultar.png"))); // NOI18N
        jButtonVisualizarGrande3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande3ActionPerformed(evt);
            }
        });

        jButtonVisualizarGrande4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call visualizar medio.png"))); // NOI18N
        jButtonVisualizarGrande4.setContentAreaFilled(false);
        jButtonVisualizarGrande4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande4.setEnabled(false);
        jButtonVisualizarGrande4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call grande.png"))); // NOI18N
        jButtonVisualizarGrande4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call grande.png"))); // NOI18N
        jButtonVisualizarGrande4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Enviar E-mail Cobrança");

        jLabel6.setText("Criar Novo Usuário");

        jLabel7.setText("Agendar Entrevista");

        jLabel8.setText("Cadastrar Projetos");

        jLabel9.setText("Agendar Reunião");

        jLabel10.setText("Cancelar Reunião");

        jLabel11.setText("Visualizar Reuniões");

        jLabel12.setText("Registrar ligações");

        jLabel13.setText("Consultar Ligações");

        jLabel14.setText("Logoff");

        jLabel15.setText("Alterar Senha");

        jButtonVisualizarProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio consulta.png"))); // NOI18N
        jButtonVisualizarProjetos.setBorder(null);
        jButtonVisualizarProjetos.setBorderPainted(false);
        jButtonVisualizarProjetos.setContentAreaFilled(false);
        jButtonVisualizarProjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarProjetos.setFocusPainted(false);
        jButtonVisualizarProjetos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar pesquisa grande.png"))); // NOI18N
        jButtonVisualizarProjetos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar pesquisa grande.png"))); // NOI18N
        jButtonVisualizarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarProjetosActionPerformed(evt);
            }
        });

        jLabel16.setText("Visualizar Projetos");

        jDesktopPane1.setLayer(jLabelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastrarGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonRecebimentosGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonSairGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarProjetos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCadastrarGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRecebimentosGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonVisualizarGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonVisualizarGrande1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVisualizarGrande2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVisualizarProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastroUsuarioGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVisualizarGrande3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastroUsuarioGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonVisualizarGrande4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSairGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastroUsuarioGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastroUsuarioGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonVisualizarGrande, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastroUsuarioGrande1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastroUsuarioGrande2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastroUsuarioGrande3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVisualizarProjetos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVisualizarGrande2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)))
                .addGap(6, 6, 6)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRecebimentosGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSairGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVisualizarGrande4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(jButtonVisualizarGrande1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVisualizarGrande3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addComponent(jButtonCadastroUsuarioGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel12)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(jLabel1)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_menu.png"))); // NOI18N
        Visualizar.setText("Controle");
        Visualizar.setEnabled(false);
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });

        Cadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/plus.png"))); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        Visualizar.add(Cadastrar);

        Visualizador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        Visualizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        Visualizador.setText("Visualizar");
        Visualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizadorActionPerformed(evt);
            }
        });
        Visualizar.add(Visualizador);

        CadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        CadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list nano.png"))); // NOI18N
        CadastroUsuario.setText("Cadastro  de usuário");
        CadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroUsuarioActionPerformed(evt);
            }
        });
        Visualizar.add(CadastroUsuario);

        Recebimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        Recebimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder.png"))); // NOI18N
        Recebimento.setText("Recebimentos");
        Recebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebimentoActionPerformed(evt);
            }
        });
        Visualizar.add(Recebimento);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario verde pequeno.png"))); // NOI18N
        jMenuItem12.setText("Agenda");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        Visualizar.add(jMenuItem12);

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Visualizar.add(Sair);

        jMenuBar2.add(Visualizar);

        jMenu6.setText("Relatórios");
        jMenu6.setEnabled(false);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        jMenuItem1.setText("Relatório padrão");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        jMenuItem2.setText("Relatório não recebido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        jMenuItem4.setText("Relatório resumido");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar.png"))); // NOI18N
        jMenuItem6.setText("Criar reunião");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar cancel.png"))); // NOI18N
        jMenuItem7.setText("Cancelar Reunião");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar consulta.png"))); // NOI18N
        jMenuItem5.setText("Consulta Reunião");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar2.add(jMenu6);

        jMenu8.setText("E-mail");
        jMenu8.setEnabled(false);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_menu.png"))); // NOI18N
        jMenuItem3.setText("E-mail");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuBar2.add(jMenu8);

        jMenu9.setText("Entrevistas");
        jMenu9.setEnabled(false);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user pequeno.png"))); // NOI18N
        jMenuItem8.setText("Agendar Entrevista");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user pequeno user.png"))); // NOI18N
        jMenuItem9.setText("Finalizar Entrevista");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuBar2.add(jMenu9);

        jMenu10.setText("Ligações");
        jMenu10.setEnabled(false);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call pequeno aten.png"))); // NOI18N
        jMenuItem10.setText("Registrar Ligações");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call pequeno visuali.png"))); // NOI18N
        jMenuItem11.setText("Consultar ligações");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem11);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(1350, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizarActionPerformed

    private void VisualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizadorActionPerformed
        new VisualizadorProfissionais().show();
    }//GEN-LAST:event_VisualizadorActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed

try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))){
//               Consultador Cl = new Consultador();
//               Cl.setVisible(true);
         enviatexto = new Consultador();
         enviatexto.setVisible(true);
         enviatexto.setState(Consultador.NORMAL);
         enviatexto.recebendo(jLabelUser.getText());
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
//        try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Comum")){
//            Consultador Cl = new Consultador();
//            Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }   
    }//GEN-LAST:event_CadastrarActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        Login Cl = new Login();
        Cl.setVisible(true);
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void CadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor"))){
            CadastroLogin Cl = new CadastroLogin();
            Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }   
    }//GEN-LAST:event_CadastroUsuarioActionPerformed

    private void RecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebimentoActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Gestor"))||(conecta.rs.getString("permissao").equals("Recebedor")||(conecta.rs.getString("permissao").equals("Admin")))){ 
//            if((conecta.rs.getString("permissao").equals("Recebedor"))||(conecta.rs.getString("permissao").equals("Recebedor1"))||(conecta.rs.getString("permissao").equals("Recebedor2"))||(conecta.rs.getString("permissao").equals("Recebedor3"))||(conecta.rs.getString("permissao").equals("Recebedor4"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor5"))||(conecta.rs.getString("permissao").equals("Recebedor6"))||(conecta.rs.getString("permissao").equals("Recebedor7"))||(conecta.rs.getString("permissao").equals("Recebedor8"))||(conecta.rs.getString("permissao").equals("Recebedor9"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor10"))||(conecta.rs.getString("permissao").equals("Recebedor11"))||(conecta.rs.getString("permissao").equals("Recebedor12"))||(conecta.rs.getString("permissao").equals("Recebedor13"))||(conecta.rs.getString("permissao").equals("Recebedor14"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor15"))||(conecta.rs.getString("permissao").equals("Recebedor16"))||(conecta.rs.getString("permissao").equals("Recebedor17"))||(conecta.rs.getString("permissao").equals("Recebedor18"))||(conecta.rs.getString("permissao").equals("Recebedor19"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor20"))||(conecta.rs.getString("permissao").equals("Recebedor21"))||(conecta.rs.getString("permissao").equals("Recebedor22"))||(conecta.rs.getString("permissao").equals("Recebedor23"))||(conecta.rs.getString("permissao").equals("Recebedor24"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor25"))||(conecta.rs.getString("permissao").equals("Recebedor26")||(conecta.rs.getString("permissao").equals("Recebedor27")))){
                enviarecebimento = new ConfirmacaoRecebimento();
                enviarecebimento.setVisible(true);
                enviarecebimento.setState(ConfirmacaoRecebimento.NORMAL);
                enviarecebimento.recebendo(jLabelUser.getText());
               // ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
             //   Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }       
//         try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Recebedor9")){
//            ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
//            Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }   
    }//GEN-LAST:event_RecebimentoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios order by data");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz ireport\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            conecta.desconecta();
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios where recebimento in ('Não recebido') order by departamento");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz ireport não\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            conecta.desconecta();
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
             try {
                 conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
             if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
//               Consultador Cl = new Consultador();
//               Cl.setVisible(true);
         enviaEmail = new EnvioEmail();
         enviaEmail.setVisible(true);
         enviaEmail.setState(Consultador.NORMAL);
         enviaEmail.recebendo(jLabelUser.getText());
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
             conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }         
//        try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Comum")){
//            EnvioEmail Cl = new EnvioEmail();
//            Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios where destinatario = 'TDP' and recebimento = 'Não recebido' order by id");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz ireport\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            conecta.desconecta();
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:       
          try {
              conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
//               Consultador Cl = new Consultador();
//               Cl.setVisible(true);
         enviaEmail = new EnvioEmail();
         enviaEmail.setVisible(true);
         enviaEmail.setState(Consultador.NORMAL);
         enviaEmail.recebendo(jLabelUser.getText());
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }       
//        try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Comum")){
//                EnvioEmail Cl = new EnvioEmail();
//                Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSairGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairGrandeActionPerformed
        // TODO add your handling code here:
        Login Cl = new Login();
        Cl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSairGrandeActionPerformed

    private void jButtonRecebimentosGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecebimentosGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Gestor"))||(conecta.rs.getString("permissao").equals("Recebedor")||(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao2").equals("Financeiro"))))){                  
//                    ||(conecta.rs.getString("permissao").equals("Recebedor2"))||(conecta.rs.getString("permissao").equals("Recebedor3"))||(conecta.rs.getString("permissao").equals("Recebedor4"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor5"))||(conecta.rs.getString("permissao").equals("Recebedor6"))||(conecta.rs.getString("permissao").equals("Recebedor7"))||(conecta.rs.getString("permissao").equals("Recebedor8"))||(conecta.rs.getString("permissao").equals("Recebedor9"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor10"))||(conecta.rs.getString("permissao").equals("Recebedor11"))||(conecta.rs.getString("permissao").equals("Recebedor12"))||(conecta.rs.getString("permissao").equals("Recebedor13"))||(conecta.rs.getString("permissao").equals("Recebedor14"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor15"))||(conecta.rs.getString("permissao").equals("Recebedor16"))||(conecta.rs.getString("permissao").equals("Recebedor17"))||(conecta.rs.getString("permissao").equals("Recebedor18"))||(conecta.rs.getString("permissao").equals("Recebedor19"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor20"))||(conecta.rs.getString("permissao").equals("Recebedor21"))||(conecta.rs.getString("permissao").equals("Recebedor22"))||(conecta.rs.getString("permissao").equals("Recebedor23"))||(conecta.rs.getString("permissao").equals("Recebedor24"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor25")||(conecta.rs.getString("permissao").equals("Recebedor26"))||(conecta.rs.getString("permissao").equals("Recebedor27")))){
                enviarecebimento = new ConfirmacaoRecebimento();
                enviarecebimento.setVisible(true);
                enviarecebimento.setState(ConfirmacaoRecebimento.NORMAL);
                enviarecebimento.recebendo(jLabelUser.getText());
               // ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
             //   Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonRecebimentosGrandeActionPerformed

    private void jButtonCadastroUsuarioGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor"))){
                CadastroLogin Cl = new CadastroLogin();
                Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonCadastroUsuarioGrandeActionPerformed

    private void jButtonVisualizarGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrandeActionPerformed
        // TODO add your handling code here:
        new VisualizadorProfissionais().show();
    }//GEN-LAST:event_jButtonVisualizarGrandeActionPerformed

    private void jButtonCadastrarGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))){
//               Consultador Cl = new Consultador();
//               Cl.setVisible(true);
         enviatexto = new Consultador();
         enviatexto.setVisible(true);
         enviatexto.setState(Consultador.NORMAL);
         enviatexto.recebendo(jLabelUser.getText());
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
//        if(enviatexto == null){
//         enviatexto = new Consultador();
//        enviatexto.setVisible(true);
//        enviatexto.recebendo(jLabelUser.getText());
//        }else{
//         enviatexto.setVisible(true);
//         enviatexto.setState(Consultador.NORMAL);
//         enviatexto.recebendo(jLabelUser.getText());
//        }
    }//GEN-LAST:event_jButtonCadastrarGrandeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CadastroDeUsuario frm = new CadastroDeUsuario(jLabelUser.getText());
                frm.setVisible(true); 
        //new CadastroDeUsuario().show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         
//            try{
//            conecta.executaSQL("select * from reuniao order by SUBSTR( datainicio, 7,4),SUBSTR( datainicio, 4,2),SUBSTR( datainicio, 1,2)");
//        JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
//            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz reuniao\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
//            JasperViewer jv = new JasperViewer(jpPrint,false);
//            jv.setVisible(true);
//            jv.toFront();
//        }catch (JRException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
//        }

           try {
               conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebesenhaa= new NovoTesteJanela();
         recebesenhaa.setVisible(true);
         recebesenhaa.setState(NovoTesteJanela.NORMAL);
         recebesenhaa.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
          //  NovoTesteJanela Cl = new NovoTesteJanela();
           //   Cl.setVisible(true);  
            
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         enviareuniao = new AgendarReuniao();
         enviareuniao.setVisible(true);
         enviareuniao.setState(AgendarReuniao.NORMAL);
         enviareuniao.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
        //AgendarReuniao Cl = new AgendarReuniao();
           //  Cl.setVisible(true); 
              
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         enviasenha = new CancelaReuniao();
         enviasenha.setVisible(true);
         enviasenha.setState(CancelaReuniao.NORMAL);
         enviasenha.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         agendaentre = new AgendaEntrevistas();
         agendaentre.setVisible(true);
         agendaentre.setState(AgendaEntrevistas.NORMAL);
         agendaentre.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         finalizaentre = new EntrevistaFinaliza();
         finalizaentre.setVisible(true);
         finalizaentre.setState(EntrevistaFinaliza.NORMAL);
         finalizaentre.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch 
                (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
           if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         ligacaofinal = new AgendaLigacoes();
         ligacaofinal.setVisible(true);
         ligacaofinal.setState(AgendaLigacoes.NORMAL);
         ligacaofinal.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
           conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        //AgendaLigacoes Cl = new AgendaLigacoes();
          //    Cl.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
         conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
         conecta.rs.first();           
         if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao").equals("Financeiro"))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebeauto = new ConsultaLigacoes();
         recebeauto.setVisible(true);
         recebeauto.setState(ConsultaLigacoes.NORMAL);
         recebeauto.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
         conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
       // ConsultaLigacoes Cl = new ConsultaLigacoes();
       //       Cl.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButtonCadastroUsuarioGrande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         enviareuniao = new AgendarReuniao();
         enviareuniao.setVisible(true);
         enviareuniao.setState(AgendarReuniao.NORMAL);
         enviareuniao.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
        //AgendarReuniao Cl = new AgendarReuniao();
           //  Cl.setVisible(true); 
              
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande1ActionPerformed

    private void jButtonCadastroUsuarioGrande2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande2ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         enviasenha = new CancelaReuniao();
         enviasenha.setVisible(true);
         enviasenha.setState(CancelaReuniao.NORMAL);
         enviasenha.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
        
       // CancelaReuniao Cl = new CancelaReuniao();
        //      Cl.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande2ActionPerformed

    private void jButtonCadastroUsuarioGrande3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande3ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebesenhaa= new NovoTesteJanela();
         recebesenhaa.setVisible(true);
         recebesenhaa.setState(NovoTesteJanela.NORMAL);
         recebesenhaa.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
         //NovoTesteJanela Cl = new NovoTesteJanela();
             // Cl.setVisible(true);  
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande3ActionPerformed

    private void jButtonVisualizarGrande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         agendaentre = new AgendaEntrevistas();
         agendaentre.setVisible(true);
         agendaentre.setState(AgendaEntrevistas.NORMAL);
         agendaentre.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande1ActionPerformed

    private void jButtonVisualizarGrande2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande2ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         finalizaentre = new EntrevistaFinaliza();
         finalizaentre.setVisible(true);
         finalizaentre.setState(EntrevistaFinaliza.NORMAL);
         finalizaentre.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
             conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande2ActionPerformed

    private void jButtonVisualizarGrande3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande3ActionPerformed
        // TODO add your handling code here:
         try {
              conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         ligacaofinal = new AgendaLigacoes();
         ligacaofinal.setVisible(true);
         ligacaofinal.setState(AgendaLigacoes.NORMAL);
         ligacaofinal.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande3ActionPerformed

    private void jButtonVisualizarGrande4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande4ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao2").equals("Financeiro"))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebeauto = new ConsultaLigacoes();
         recebeauto.setVisible(true);
         recebeauto.setState(ConsultaLigacoes.NORMAL);
         recebeauto.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
       // ConsultaLigacoes Cl = new ConsultaLigacoes();
           //   Cl.setVisible(true);
    }//GEN-LAST:event_jButtonVisualizarGrande4ActionPerformed

    private void jButtonVisualizarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarProjetosActionPerformed
        // TODO add your handling code here:
//         try {
//            conecta.conectaBanco();
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();           
//            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao").equals("Gestor"))){
//             //  Consultador Cl = new Consultador();
//            //   Cl.setVisible(true);
//         recebeautoo = new AgendaTelefonica();
//         recebeautoo.setVisible(true);
//         recebeautoo.setState(AgendaTelefonica.NORMAL);
//         recebeautoo.recebendo(jLabelUser.getText()); 
//         
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//            conecta.desconecta();
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }

         new VisualizadorPro().show();
        
        
        
    }//GEN-LAST:event_jButtonVisualizarProjetosActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
         try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao").equals("Gestor"))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebeautoo = new AgendaTelefonica();
         recebeautoo.setVisible(true);
         recebeautoo.setState(AgendaTelefonica.NORMAL);
         recebeautoo.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     * C://Users/marilialc/Documents/NetBeansProjects/MinhaAplicacao/ireport
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem CadastroUsuario;
    private javax.swing.JMenuItem Recebimento;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem Visualizador;
    private javax.swing.JMenu Visualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastrarGrande;
    private javax.swing.JButton jButtonCadastroUsuarioGrande;
    private javax.swing.JButton jButtonCadastroUsuarioGrande1;
    private javax.swing.JButton jButtonCadastroUsuarioGrande2;
    private javax.swing.JButton jButtonCadastroUsuarioGrande3;
    private javax.swing.JButton jButtonRecebimentosGrande;
    private javax.swing.JButton jButtonSairGrande;
    private javax.swing.JButton jButtonVisualizarGrande;
    private javax.swing.JButton jButtonVisualizarGrande1;
    private javax.swing.JButton jButtonVisualizarGrande2;
    private javax.swing.JButton jButtonVisualizarGrande3;
    private javax.swing.JButton jButtonVisualizarGrande4;
    private javax.swing.JButton jButtonVisualizarProjetos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
