/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.TimeZone;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author vinicius
 */
public class NovoTesteJanela extends javax.swing.JFrame {
ConnectionConsulta conecta = new ConnectionConsulta();

//DateFormat df = DateFormat.getDateInstance();

    /**
     * Creates new form NovoTesteJanela
     */
    public NovoTesteJanela() {
        initComponents();
          conecta.conectaBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPessoa = new javax.swing.JComboBox<>();
        jButtonSolicitante = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setEnabled(false);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEnabled(false);

        jDateChooser1.setDateFormatString("yyyy/MM/dd");

        jDateChooser2.setDateFormatString("yyyy/MM/dd");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        jLabel3.setText("Consultar Reuniões:");

        jComboBoxPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC / Priscila", "Adriana", "Andreia", "Antônio Carlos ", "Bruno", "Contabil", "Edilene", "Gustavo", "Katia", "Louise", "Natalia/ Contadores", "Priscila", "Priscila / Andréia", "Todos contadores", "Vera" }));

        jButtonSolicitante.setText("Consulta por solicitante");
        jButtonSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitanteActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuario:");

        jTextFieldUsuario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBoxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSolicitante))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(jTextField2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldUsuario))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSolicitante)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(425, 259));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{       
            // String fechaObtenida = df.format(jDateChooser1.getDate());
            // jTextField1.setText(fechaObtenida);
            
            String dia = Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH) + 1);
            String year = Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
            String fecha = (year + "/" + mes+ "/" + dia);
            jTextField1.setText(fecha);

            //String fechaObtenidaa = df.format(jDateChooser2.getDate());           
            //jTextField2.setText(fechaObtenidaa);
            String day = Integer.toString(jDateChooser2.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mess = Integer.toString(jDateChooser2.getCalendar().get(Calendar.MONTH) + 1);
            String anoo = Integer.toString(jDateChooser2.getCalendar().get(Calendar.YEAR));
            String exec = (anoo + "/" + mess+ "/" +day);
            jTextField2.setText(exec);
            //conecta.executaSQL("select * from reuniao where STR_TO_DATE(datainicio, '%d/%m/%Y') BETWEEN '" + jDateChooser1.getDate().toString() + "' and '" + jDateChooser2.getDate().toString() + "' order by SUBSTR( datainicio, 7,4),SUBSTR( datainicio, 4,2),SUBSTR( datainicio, 1,2)");
            conecta.executaSQL("select * from reuniao where STR_TO_DATE(datainicio, '%d/%m/%Y') BETWEEN '" + jTextField1.getText() + "' and '" + jTextField2.getText() + "' order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
            //conecta.executaSQL("select * from reuniao where solicitante ='" + jComboBoxPessoa.getSelectedItem()+"'" );
            //conecta.executaSQL("select * from reuniao where date_format(datainicio, '%d/%m/%Y') BETWEEN '" + jTextField1.getText() + "' and '" + jTextField2.getText() + "' order by datainicio");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz reuniao\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.show();
           // jv.setVisible(true);
           // jv.toFront();
           
           //abrindo maximizado
           //viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitanteActionPerformed
        // TODO add your handling code here:
        try{       
            // String fechaObtenida = df.format(jDateChooser1.getDate());
            // jTextField1.setText(fechaObtenida);
            
            String dia = Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH) + 1);
            String year = Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
            String fecha = (year + "/" + mes+ "/" + dia);
            jTextField1.setText(fecha);

            //String fechaObtenidaa = df.format(jDateChooser2.getDate());           
            //jTextField2.setText(fechaObtenidaa);
            String day = Integer.toString(jDateChooser2.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mess = Integer.toString(jDateChooser2.getCalendar().get(Calendar.MONTH) + 1);
            String anoo = Integer.toString(jDateChooser2.getCalendar().get(Calendar.YEAR));
            String exec = (anoo + "/" + mess+ "/" +day);
            jTextField2.setText(exec);
            //conecta.executaSQL("select * from reuniao where STR_TO_DATE(datainicio, '%d/%m/%Y') BETWEEN '" + jDateChooser1.getDate().toString() + "' and '" + jDateChooser2.getDate().toString() + "' order by SUBSTR( datainicio, 7,4),SUBSTR( datainicio, 4,2),SUBSTR( datainicio, 1,2)");
            conecta.executaSQL("select * from reuniao where STR_TO_DATE(datainicio, '%d/%m/%Y') BETWEEN '" + jTextField1.getText() + "' and '" + jTextField2.getText() + "' order by SUBSTR( datainicio, -4,4),SUBSTR( datainicio, -7,2),SUBSTR( datainicio, -10,2),SUBSTR( datainicio, -9,1),SUBSTR( datainicio, -8,1)");
            conecta.executaSQL("select * from reuniao where solicitante ='" + jComboBoxPessoa.getSelectedItem()+"'" );
            //conecta.executaSQL("select * from reuniao where date_format(datainicio, '%d/%m/%Y') BETWEEN '" + jTextField1.getText() + "' and '" + jTextField2.getText() + "' order by datainicio");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz reuniao\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.show();
           // jv.setVisible(true);
           // jv.toFront();
           
           //abrindo maximizado
           //viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jButtonSolicitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoTesteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoTesteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoTesteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoTesteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoTesteJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSolicitante;
    private javax.swing.JComboBox<String> jComboBoxPessoa;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe){
        jTextFieldUsuario.setText(recebe);
    }   
}